export default [
  {
    href: 'https://prometheus.io/',
    src: 'prometheus_logo.png',
    name: 'Prometheus Operator',
    desc: 'The current standard in collecting container application metrics',
  },
  {
    href: 'https://grafana.com/oss/loki/',
    src: 'loki_logo.svg',
    name: 'Loki',
    desc: 'The next standard in collecting container application logs',
  },
  {
    href: 'https://grafana.com/',
    src: 'grafana_logo.png',
    name: 'Grafana',
    desc: 'The famous dashboard for viewing application traces, metrics and logs',
  },
  {
    href: 'https://istio.io/',
    src: 'istio_logo.png',
    name: 'Istio',
    desc: 'The service mesh framework with end to end transit encryption and much more',
  },
  {
    href: 'https://www.jaegertracing.io/',
    src: 'jaeger_logo.png',
    name: 'Jaeger',
    desc: 'End-to-end distributed tracing and monitor for complex distributed systems',
  },
  {
    href: 'https://kiali.io/',
    src: 'kiali_logo.png',
    name: 'Kiali',
    desc: 'Observe the Istio service mesh relations and connections',
  },
  {
    href: 'https://www.openpolicyagent.org/',
    src: 'opa_logo.png',
    name: 'OPA',
    desc: 'Policy-based control for cloud native environments',
  },
  {
    href: 'https://openid.net/',
    src: 'openid_logo.svg',
    name: 'Oauth2 / OpenID',
    desc: 'Authentication of users against any OIDC provider, or Active Directory / LDAP',
  },
  {
    href: 'https://www.keycloak.org/',
    src: 'keycloak_logo.svg',
    name: 'Keycloak',
    desc: 'Open source Identity and Access Management for modern applications and services',
  },
  {
    href: 'https://github.com/helm/charts/tree/master/stable/external-dns',
    src: 'kubernetes_logo.svg',
    name: 'External DNS',
    desc: 'Making sure your service ips are found on the internet using hostnames',
  },
  {
    href: 'https://knative.dev/',
    src: 'knative_logo.png',
    name: 'Knative',
    desc: 'Deploy and manage modern serverless workloads like functions and auto scalable container deployments',
  },
  {
    href: 'https://goharbor.io/',
    src: 'harbor_logo.png',
    name: 'Harbor',
    desc: 'Container image registry with role-based access control, image scanning and image signing',
  },
  {
    href: 'https://velero.io/',
    src: 'velero_logo.png',
    name: 'Velero',
    desc: 'Back up Kubernetes objects and Persistent Volumes',
  },
  {
    href: 'https://gitlab.com/',
    src: 'gitlab_logo.svg',
    name: 'GitLab',
    desc: 'Choose your favorite CI/CD platform',
  },
  {
    href: 'https://drone.io/',
    src: 'drone_logo.svg',
    name: 'Drone',
    desc: 'Choose your favorite CI/CD platform',
  },
  {
    href: 'https://kubernetes.io/docs/concepts/services-networking/ingress/',
    src: 'ingress_logo.png',
    name: 'Ingress Control',
    desc: 'Create and configure supporting Cloud resources for ingress',
  },
  {
    href: 'https://letsencrypt.org/',
    src: 'letsencrypt_logo.svg',
    name: "Let's Encrypt",
    desc: 'A nonprofit Certificate Authority providing industry recognized TLS certificates',
  },
  {
    href: 'https://www.weave.works/oss/scope/',
    src: 'weave_logo.png',
    name: 'Weave Scope',
    desc: 'Understand your application quickly by seeing it in a real time interactive display',
  },
  {
    href: 'https://www.sitespeed.io/',
    src: 'sitespeed.png',
    name: 'Site Speed',
    desc: 'Monitor and measure the performance of your web site',
  },
]
