export default [
  {
    href: 'https://istio.io/',
    src: 'istio-logo.svg',
    name: 'Istio',
    desc: 'The service mesh framework with end to end transit encryption and much more',
  },
  {
    href: 'https://knative.dev/',
    src: 'knative.png',
    name: 'Knative',
    desc: 'Deploy and manage modern serverless workloads like functions and auto scalable container deployments',
  },
  {
    href: 'https://www.openpolicyagent.org/',
    src: 'opa-logo.svg',
    name: 'OPA',
    desc: 'Policy-based control for cloud native environments',
  },
  {
    href: 'https://prometheus.io/',
    src: 'prometheus-logo.svg',
    name: 'Prometheus',
    desc: 'The current standard in collecting container application metrics',
  },
  {
    href: 'https://grafana.com/oss/loki/',
    src: 'loki-logo.svg',
    name: 'Loki',
    desc: 'The next standard in collecting container application logs',
  },
  {
    href: 'https://grafana.com/',
    src: 'grafana-logo.svg',
    name: 'Grafana',
    desc: 'The famous dashboard for viewing application traces, metrics and logs',
  },
  {
    href: 'https://goharbor.io/',
    src: 'harbor-logo.svg',
    name: 'Harbor',
    desc: 'Container image registry with role-based access control, image scanning and image signing',
  },
  {
    href: 'https://www.vaultproject.io/',
    src: 'vault-logo.svg',
    name: 'HashiCorp Vault',
    desc: 'Manage Secrets and Protect Sensitive Data',
  },
  {
    href: 'https://bitnami.com/kubernetes/kubeapps',
    src: 'kubeapps.png',
    name: 'Bitnami Kubeapps',
    desc: 'Web-based UI for launching and managing applications on Kubernetes',
  },
  {
    href: 'https://cert-manager.io/',
    src: 'cert-manager.svg',
    name: 'Certmanager',
    desc: 'Securely provide certificates to applications working within your cluster',
  },
  {
    href: 'https://github.com/helm/charts/tree/master/stable/external-dns',
    src: 'dns-logo.svg',
    name: 'External DNS',
    desc: 'Making sure your service ips are found on the internet using hostnames',
  },
  {
    href: 'https://drone.io/',
    src: 'drone-logo.svg',
    name: 'Drone',
    desc: 'Drone is a self-service Continuous Integration platform for busy development teams',
  },
  {
    href: 'https://gitea.io/en-us/',
    src: 'gitea-logo.svg',
    name: 'Gitea',
    desc: 'A painless self-hosted Git service',
  },
  {
    href: 'https://www.keycloak.org/',
    src: 'keycloak-logo.svg',
    name: 'Keycloak',
    desc: 'Open source Identity and Access Management for modern applications and services',
  },
  {
    href: 'https://letsencrypt.org/',
    src: 'letsencrypt-logo.svg',
    name: "Let's Encrypt",
    desc: 'A nonprofit Certificate Authority providing industry recognized TLS certificates',
  },
  {
    href: 'https://www.jaegertracing.io/',
    src: 'jaeger-logo.svg',
    name: 'Jaeger',
    desc: 'End-to-end distributed tracing and monitor for complex distributed systems',
  },
  {
    href: 'https://kiali.io/',
    src: 'kiali-logo.svg',
    name: 'Kiali',
    desc: 'Observe the Istio service mesh relations and connections',
  },
  {
    href: 'https://openid.net/',
    src: 'openid-logo.svg',
    name: 'Oauth2 / OpenID',
    desc: 'Authenticate users against any OIDC provider',
  },
  {
    href: 'https://velero.io/',
    src: 'velero-logo.svg',
    name: 'Velero',
    desc: 'Back up Kubernetes objects and Persistent Volumes',
  },
  {
    href: 'https://github.com/kubernetes/ingress-nginx',
    src: 'nginx.png',
    name: 'Nginx Ingress',
    desc: 'Create and manage external access to the services in your clusters',
  },
]
